In [1]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv(r"C:\Users\Fmc\Desktop\Call-Center-Dataset.csv")

In [5]:
df.head()

,Call Id,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
0,ID0001,Diane,2021-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0
1,ID0002,Becky,2021-01-01,09:12:58,Technical Support,Y,N,70.0,00:04:02,3.0
2,ID0003,Stewart,2021-01-01,09:47:31,Contract related,Y,Y,10.0,00:02:11,3.0
3,ID0004,Greg,2021-01-01,09:47:31,Contract related,Y,Y,53.0,00:00:37,2.0
4,ID0005,Becky,2021-01-01,10:00:29,Payment related,Y,Y,95.0,00:01:00,3.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Call Id                     5000 non-null   object
 1   Agent                       5000 non-null   object
 2   Date                        5000 non-null   object
 3   Time                        5000 non-null   object
 4   Topic                       5000 non-null   object
 5   Answered (Y/N)              5000 non-null   object
 6   Resolved                    5000 non-null   object
 7   Speed of answer in seconds  4054 non-null   float64
 8   AvgTalkDuration             4054 non-null   object
 9   Satisfaction rating         4054 non-null   float64
dtypes: float64(2), object(8)
memory usage: 390.8+ KB

In [7]:
df.describe()

       Speed of answer in seconds  Satisfaction rating
count                 4054.000000          4054.000000
mean                    67.520720             3.403552
std                     33.592872             1.212220
min                     10.000000             1.000000
25%                     39.000000             3.000000
50%                     68.000000             3.000000
75%                     97.000000             4.000000
max                    125.000000             5.000000

In [8]:
df.isnull().sum()

Call Id                         0
Agent                           0
Date                            0
Time                            0
Topic                           0
Answered (Y/N)                  0
Resolved                        0
Speed of answer in seconds    946
AvgTalkDuration               946
Satisfaction rating           946
dtype: int64

In [9]:
df[df.isnull().any(axis=1)]

,Call Id,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
5,ID0006,Stewart,2021-01-01,10:00:29,Technical Support,N,N,NaN,NaN,NaN
10,ID0011,Joe,2021-01-01,11:15:22,Payment related,N,N,NaN,NaN,NaN
17,ID0018,Becky,2021-01-01,11:57:07,Admin Support,N,N,NaN,NaN,NaN
18,ID0019,Jim,2021-01-01,12:01:26,Streaming,N,N,NaN,NaN,NaN
22,ID0023,Martha,2021-01-01,12:02:53,Technical Support,N,N,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
4991,ID4992,Joe,2021-03-31,14:13:55,Streaming,N,N,NaN,NaN,NaN
4992,ID4993,Joe,2021-03-31,14:18:14,Admin Support,N,N,NaN,NaN,NaN
4993,ID4994,Greg,2021-03-31,14:58:34,Contract related,N,N,NaN,NaN,NaN
4994,ID4995,Dan,2021-03-31,15:33:07,Payment related,N,N,NaN,NaN,NaN
4999,ID5000,Diane,2021-03-31,17:39:50,Contract related,N,N,NaN,NaN,NaN

In [10]:
#Missing Values indicates calls were not answered

In [13]:
#Impute missing values 

df["Speed of answer in seconds"] = df["Speed of answer in seconds"].fillna(0)

In [16]:
df["AvgTalkDuration"] = df["AvgTalkDuration"].fillna("00:00:00")

In [17]:
df["Satisfaction rating"] = df["Satisfaction rating"].fillna(0)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Call Id                     5000 non-null   object
 1   Agent                       5000 non-null   object
 2   Date                        5000 non-null   object
 3   Time                        5000 non-null   object
 4   Topic                       5000 non-null   object
 5   Answered (Y/N)              5000 non-null   object
 6   Resolved                    5000 non-null   object
 7   Speed of answer in seconds  5000 non-null   float64
 8   AvgTalkDuration             5000 non-null   object
 9   Satisfaction rating         5000 non-null   float64
dtypes: float64(2), object(8)
memory usage: 390.8+ KB